/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessConfig = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const FaqItem = IDL.Record({
  'question' : IDL.Text,
  'order' : IDL.Nat16,
  'answer' : IDL.Text,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat16,
});

export const idlService = IDL.Service({
  'addFaq' : IDL.Func([IDL.Nat16, IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat16, IDL.Text], [IDL.Nat], []),
  'getBusinessConfig' : IDL.Func([], [BusinessConfig], ['query']),
  'getFaqs' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'removeFaq' : IDL.Func([IDL.Nat16], [], []),
  'removeTestimonial' : IDL.Func([IDL.Nat], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBusinessConfig' : IDL.Func([BusinessConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessConfig = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FaqItem = IDL.Record({
    'question' : IDL.Text,
    'order' : IDL.Nat16,
    'answer' : IDL.Text,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat16,
  });
  
  return IDL.Service({
    'addFaq' : IDL.Func([IDL.Nat16, IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([IDL.Text, IDL.Nat16, IDL.Text], [IDL.Nat], []),
    'getBusinessConfig' : IDL.Func([], [BusinessConfig], ['query']),
    'getFaqs' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'removeFaq' : IDL.Func([IDL.Nat16], [], []),
    'removeTestimonial' : IDL.Func([IDL.Nat], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateBusinessConfig' : IDL.Func([BusinessConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };