/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessConfig {
  'tagline' : string,
  'name' : string,
  'whatsappNumber' : string,
  'address' : string,
  'phone' : string,
}
export interface FaqItem {
  'question' : string,
  'order' : number,
  'answer' : string,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'name' : string,
  'timestamp' : Time,
  'rating' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addFaq' : ActorMethod<[number, string, string], undefined>,
  'addTestimonial' : ActorMethod<[string, number, string], bigint>,
  'getBusinessConfig' : ActorMethod<[], BusinessConfig>,
  'getFaqs' : ActorMethod<[], Array<FaqItem>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'removeFaq' : ActorMethod<[number], undefined>,
  'removeTestimonial' : ActorMethod<[bigint], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateBusinessConfig' : ActorMethod<[BusinessConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];